// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1B2mWdNoKsGL6GJdHdW4B7kC1i88NS0w',
    appId: '1:300345626968:web:6a42e5b26400a4c56d152d',
    messagingSenderId: '300345626968',
    projectId: 'monch-lifestasty',
    authDomain: 'monch-lifestasty.firebaseapp.com',
    storageBucket: 'monch-lifestasty.appspot.com',
    measurementId: 'G-C3JMC9VYQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqMJGCuJCNd99OGloAmUjM2g68qLYh3l4',
    appId: '1:300345626968:android:735e2c39b0e297e06d152d',
    messagingSenderId: '300345626968',
    projectId: 'monch-lifestasty',
    storageBucket: 'monch-lifestasty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJAGuPjXGuLDsdO6O-BlOmCTwlvhkWR_8',
    appId: '1:300345626968:ios:f17d89d73446bdf56d152d',
    messagingSenderId: '300345626968',
    projectId: 'monch-lifestasty',
    storageBucket: 'monch-lifestasty.appspot.com',
    androidClientId: '300345626968-i8rsei8qmq92d7amrgi7gg45bkvs87is.apps.googleusercontent.com',
    iosClientId: '300345626968-p0kvg4foak2gt5a3d5v65e3ho6oplssb.apps.googleusercontent.com',
    iosBundleId: 'com.example.monch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJAGuPjXGuLDsdO6O-BlOmCTwlvhkWR_8',
    appId: '1:300345626968:ios:f17d89d73446bdf56d152d',
    messagingSenderId: '300345626968',
    projectId: 'monch-lifestasty',
    storageBucket: 'monch-lifestasty.appspot.com',
    androidClientId: '300345626968-i8rsei8qmq92d7amrgi7gg45bkvs87is.apps.googleusercontent.com',
    iosClientId: '300345626968-p0kvg4foak2gt5a3d5v65e3ho6oplssb.apps.googleusercontent.com',
    iosBundleId: 'com.example.monch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1B2mWdNoKsGL6GJdHdW4B7kC1i88NS0w',
    appId: '1:300345626968:web:61b982c041c8601b6d152d',
    messagingSenderId: '300345626968',
    projectId: 'monch-lifestasty',
    authDomain: 'monch-lifestasty.firebaseapp.com',
    storageBucket: 'monch-lifestasty.appspot.com',
    measurementId: 'G-K8TN0EK4Q4',
  );

}